### PR TITLE
Kinetic panda vis

### PR DESCRIPTION
**Pull request by mlautman**
- Replacing images with screenshots of updated panda meshes
- Minor clean up of tutorial

### CODE REVIEW

**Comment by mlautman** [comment]
[live](http://tutorials.picknik.ai/doc/visualization/visualization_tutorial.html)

**Comment by davetcoleman** [comment]
Why are the two images under "Moving into collision" section so much smaller than the rest?

**Comment by mlautman** [comment]
@davetcoleman fixed

**Comment by mlautman** [comment]
@davetcoleman I've definitely been using the squash and merge button. Am I possibly using it wrong?

**Comment by davetcoleman** [comment]
Nevermind, looking at the git commit history its clear you're using that button

**Pull request merged**
